name: Union of crabs and seagulls
description: |-
  При заселении в отель вы столкнулись с проблемой — на ресепшене никого не было. Чайки-администраторы ушли пить чай. А уже хочется пойти искупаться в бассейне.

  Вы краем уха слышали, что вас будут заселять сразу всех группой. Может быть уже заселили?

  Похоже придётся влезть в компьютер и проверить информацию о постояльцах… А может там есть информация про сотрудников?

author: greg0r0
category: web
flag: crab{UN10N1z3d_s34gulls}
server_port: null
is_http: true
domain_prefix: null
