version: '3.8'

services:
  frontend:
    build: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: backend
    environment:
      - FLAG=Ostrovok{Example_flag18}
    expose:
      - 5000
