version: "3"
services:
  task:
    build: service/
    expose:
      - 80
    ports:
      - "7821:80"

  bot:
    build: bot/
    links:
      - task
    depends_on:
      - task
    privileged: true
