services:
  llama_server:
    build: ./llama_server
    expose:
      - "8000"
    volumes:
      - models:/models
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 10s
      retries: 99999
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mongo:
    image: mongo:latest
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db
    restart: always

  telegram_bot:
    build: ./telegram_bot
    environment:
      - FLAG_ENC_KEY=92LkXZb9Co1yh9v8D4vXdFDYuMTCcKLGH0kugYhYieOsUfPz1uXvkZ1A1vehAIMU
      - FLAG_SALT=34pv5o345vi3451
      - FLAG_PATTERN=crab{{d0nt_us3_stup1d_llm_m0d3ls_{sign}}}
      - TELEGRAM_TOKEN=xxx
      - MONGO_URI=mongodb://root:example@mongo:27017
      - LLAMA_SERVER_URL=http://llama_server:8000/v1
    depends_on:
      llama_server:
        condition: service_healthy
      mongo:
        condition: service_started
    restart: always

volumes:
  mongo_data:
  models:
