name: "Sanity Check: Заселяемся в отель"
description: |-
  На лазурном берегу моря, где волны нежно шепчутся с песком, чайки давно облюбовали уютный отель, устроенный прямо на скалах. 
  В этом прибрежном царстве они были полноправными хозяйками, и, честно говоря, крабов не слишком жаловали. 
  Но однажды к берегу подтянулись хитроумные крабы, решившие, что и им пора отдохнуть на берегу и сделать crab rave под лучами солнца. 
  Чайкам это не понравилось, но бизнес есть бизнес: они не только решили взять с крабов плату за жильё, но и при случае подстроить им парочку мелких пакостей.

  Первой неприятностью стало то, что чайки **настойчиво просят ознакомится** с правилами нахождения в отеле. На столько настойчиво, что не пускают дальше, даже не дают подключится к WiFi!


author: '@greg0r0'
category: web
flag: crab{w3lc0m3_t0_ChaykaHotels}
server_port: null
is_http: false
domain_prefix: null
is_dynamic: false
